hmrc/cbcr

app/uk/gov/hmrc/cbcr/controllers/SubscriptionDataController.scala, conf/app.routes, conf/application-json-logger-debug.xml, conf/application-json-logger.xml, conf/logback.xml, test/uk/gov/hmrc/cbcr/controllers/SubscriptionDataControllerSpec.scala
=> Updated route name and made more generic

project/MicroService.scala
Added in default port number so people don't have to remember it ;)
=> [CC]Added in default port number to sbt build file

app/uk/gov/hmrc/cbcr/services/DocRefIdClearService.scala, test/uk/gov/hmrc/cbcr/services/DocRefIdClearServiceSpec.scala
=> Revert "changed delimeter for docrefidclear service to __"

app/uk/gov/hmrc/cbcr/Module.scala, app/uk/gov/hmrc/cbcr/audit/AuditConnector.scala, app/uk/gov/hmrc/cbcr/auth/CBCRAuth.scala, app/uk/gov/hmrc/cbcr/config/GenericAppConfig.scala, app/uk/gov/hmrc/cbcr/connectors/DESConnector.scala, app/uk/gov/hmrc/cbcr/connectors/EmailConnector.scala, app/uk/gov/hmrc/cbcr/controllers/CBCIdController.scala, app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/package.scala, project/MicroService.scala, project/MicroServiceBuild.scala, project/plugins.sbt, test/uk/gov/hmrc/cbcr/auth/CBCRAuthSpec.scala, test/uk/gov/hmrc/cbcr/controllers/BusinessPartnerRecordControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/CBCIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/CBCREmailControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/DocRefIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/FileUploadResponseControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/MessageRefIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/MockAuth.scala, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/SubscriptionDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/package.scala, test/uk/gov/hmrc/cbcr/services/AuditSubscriptionServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/DocRefIdClearServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/EmailServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/RemoteSubscriptionSpec.scala
=> DLS-79: Play-2.5.19 upgrade changes

app/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataController.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, conf/app.routes, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala
=> DLS-115: Implemented new business rule to prevent multiple file upload for the original submission within the same reporting period

repository.yaml
=> CBCR-879: add repo to services catalogue

app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, conf/test.routes
=> created test-only endpoint to drop mongo collection

app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala
=> using remove instead of drop

app/uk/gov/hmrc/cbcr/Module.scala, app/uk/gov/hmrc/cbcr/repositories/DocRefIdRepository.scala, app/uk/gov/hmrc/cbcr/repositories/ReactiveDocRefIdRepository.scala, app/uk/gov/hmrc/cbcr/services/AdminService.scala, conf/app.routes, project/MicroServiceBuild.scala, project/plugins.sbt
- [ x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [ x]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [x ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
- [ x]  I've run a dependency check to ensure all dependencies are up to date
=> Doc ref if length checking

app/uk/gov/hmrc/cbcr/services/AdminService.scala
=> DLS-AdminEndpointChange

app/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataController.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, conf/app.routes
Implemented the logic for Multiple File Upload business rule
=> DLS-290: Implemented the logic for Multiple File Upload business rule

app/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataController.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, conf/app.routes
**Bug fix** (delete as appropriate)
=> DLS-522: Implemented the long term fix for the multiple file upload edge case scenario

app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala
=> DLS-476 [AK,CG] - Logged when record None

project/MicroServiceBuild.scala
=> [CU][DLS-610]: Downgrading akka persistence and reactive mongo

app/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataController.scala, app/uk/gov/hmrc/cbcr/services/AdminService.scala, conf/app.routes
=> DLS-555: WIP

app/uk/gov/hmrc/cbcr/services/CBCIdGenerator.scala, app/uk/gov/hmrc/cbcr/services/LocalSubscription.scala, app/uk/gov/hmrc/cbcr/services/SubscriptionHandler.scala, conf/application.conf, project/MicroServiceBuild.scala, test/uk/gov/hmrc/cbcr/actors/CBCIdGeneratorSpec.scala, test/uk/gov/hmrc/cbcr/controllers/CBCIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/services/LocalSubscriptionSpec.scala
=> Revert "[CU][DLS-673]: Upgrading mongo libraries and removing akka functionality"

app/uk/gov/hmrc/cbcr/controllers/DocRefIdController.scala, app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/repositories/DocRefIdRepository.scala, app/uk/gov/hmrc/cbcr/repositories/SubscriptionDataRepository.scala, app/uk/gov/hmrc/cbcr/services/AdminService.scala, conf/app.routes, conf/test.routes
=> DLS-760:added endpoint to validate docRefId validity

app/uk/gov/hmrc/cbcr/controllers/DocRefIdController.scala, app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, conf/app.routes, conf/test.routes, test/uk/gov/hmrc/cbcr/controllers/DocRefIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/services/RemoteSubscriptionSpec.scala
=> DLS-760-FIX: Fixed test error caused due to regex parsing

app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, app/uk/gov/hmrc/cbcr/services/AdminService.scala, conf/app.routes, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala
=> DLS-919: Added another admin endpoint

project/MicroServiceBuild.scala
=> DLS-1096: Upgrading dependencies and plugins. 

project/MicroServiceBuild.scala, test/uk/gov/hmrc/cbcr/auth/CBCRAuthSpec.scala, test/uk/gov/hmrc/cbcr/controllers/BusinessPartnerRecordControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/CBCIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/CBCREmailControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/DocRefIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/FileUploadResponseControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/MessageRefIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/SubscriptionDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/models/ReportingEntityDataSpec.scala, test/uk/gov/hmrc/cbcr/services/AuditSubscriptionServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/DocRefIdClearServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/EmailServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/LocalSubscriptionSpec.scala, test/uk/gov/hmrc/cbcr/services/RemoteSubscriptionSpec.scala, test/uk/gov/hmrc/cbcr/services/RunModeSpec.scala
=> DLS-1102: Removed hmrctest

project/MicroServiceBuild.scala, test/uk/gov/hmrc/cbcr/auth/CBCRAuthSpec.scala, test/uk/gov/hmrc/cbcr/controllers/BusinessPartnerRecordControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/CBCIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/CBCREmailControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/DocRefIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/FileUploadResponseControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/MessageRefIdControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/controllers/SubscriptionDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/models/ReportingEntityDataSpec.scala, test/uk/gov/hmrc/cbcr/services/AuditSubscriptionServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/DocRefIdClearServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/EmailServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/LocalSubscriptionSpec.scala, test/uk/gov/hmrc/cbcr/services/RemoteSubscriptionSpec.scala, test/uk/gov/hmrc/cbcr/services/RunModeSpec.scala, test/uk/gov/hmrc/cbcr/util/UnitSpec.scala
=> DLS-1102: Reinclude UnitSpec

project/MicroServiceBuild.scala
DLS-1322 -Update auth-client version
**Bug fix ** 
auth-client version has been updated to 2.31.0-play-26(minor) for cbcr
=> DLS-1322 -CBC Tax platform update

project/MicroServiceBuild.scala
**Bug fix ** 
Removed Unused Libraries
=> DLS-1032 Review libraries used by CBC

app/uk/gov/hmrc/cbcr/connectors/DESConnector.scala, test/uk/gov/hmrc/cbcr/connectors/DESConnectorSpec.scala
=> Dls 1486 Change DES 429 into 503

project/MicroServiceBuild.scala, project/build.properties, project/plugins.sbt
=> [CU][DLS-1836]: Library upgrades

app/uk/gov/hmrc/cbcr/connectors/DESConnector.scala
=> [CU][DLS-2143]: Remove sensitive information from the logs

build.sbt, project/build.properties, project/plugins.sbt
=> [CU][DLS-2416]: Library upgrades

app/uk/gov/hmrc/cbcr/Module.scala, app/uk/gov/hmrc/cbcr/auth/CBCRAuth.scala, app/uk/gov/hmrc/cbcr/connectors/DESConnector.scala, app/uk/gov/hmrc/cbcr/connectors/EmailConnector.scala, app/uk/gov/hmrc/cbcr/controllers/BusinessPartnerRecordController.scala, app/uk/gov/hmrc/cbcr/controllers/CBCIdController.scala, app/uk/gov/hmrc/cbcr/controllers/CBCREmailController.scala, app/uk/gov/hmrc/cbcr/controllers/DocRefIdController.scala, app/uk/gov/hmrc/cbcr/controllers/FileUploadResponseController.scala, app/uk/gov/hmrc/cbcr/controllers/MessageRefIdController.scala, app/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataController.scala, app/uk/gov/hmrc/cbcr/controllers/SubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/repositories/SubscriptionDataRepository.scala, app/uk/gov/hmrc/cbcr/services/AdminService.scala, app/uk/gov/hmrc/cbcr/services/AuditSubscriptionService.scala, app/uk/gov/hmrc/cbcr/services/EmailService.scala, app/uk/gov/hmrc/cbcr/services/LocalSubscription.scala, app/uk/gov/hmrc/cbcr/services/RemoteSubscription.scala, app/uk/gov/hmrc/cbcr/services/RetrieveReportingEntityService.scala, build.sbt, conf/testOnlyDoNotUseInAppConf.routes, project/build.properties, project/plugins.sbt, test/uk/gov/hmrc/cbcr/connectors/DESConnectorSpec.scala, test/uk/gov/hmrc/cbcr/connectors/EmailConnectorSpec.scala
=> [CU][DLS-3034]: Library upgrades + scala 2.12 + sbt 1.3.13

app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, test/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepoSpec.scala
=> Partial corrections fix

app/uk/gov/hmrc/cbcr/models/CBCId.scala, app/uk/gov/hmrc/cbcr/models/DocRefID.scala, app/uk/gov/hmrc/cbcr/models/ReportingEntityData.scala, app/uk/gov/hmrc/cbcr/repositories/DocRefIdRepository.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/models/DocRefIdSpec.scala, test/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepoSpec.scala, test/uk/gov/hmrc/cbcr/services/AdminServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/RetrieveReportingEntityServiceSpec.scala
=> [CU][HTSD-2]: Add optional currency code to ReportingEntity model

README.md, app/uk/gov/hmrc/cbcr/models/ReportingEntityData.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepoSpec.scala, test/uk/gov/hmrc/cbcr/services/AdminServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/RetrieveReportingEntityServiceSpec.scala
=> [CU][HTSD-23]: Saving start/end dates from entity reporting period

app/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataController.scala, app/uk/gov/hmrc/cbcr/models/DatesOverlap.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, conf/app.routes, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepoSpec.scala, test/uk/gov/hmrc/cbcr/util/UnitSpec.scala
=> [CU][HTSD-22, HTSD-24, HTSD-26]: Dates overlapping rules + backward compatibility

app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, conf/test.routes, test/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepoSpec.scala
HTSD-33 - Test endpoint created for deleting reportingPeriod
New feature
Test endpoint created for deleting reportingPeriod
=> HTSD-33 - Test endpoint created for deleting reportingPeriod

README.md, app/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataController.scala, app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/models/DatesOverlap.scala, app/uk/gov/hmrc/cbcr/models/ReportingEntityData.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, conf/app.routes, conf/test.routes, test/uk/gov/hmrc/cbcr/controllers/ReportingEntityDataControllerSpec.scala, test/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepoSpec.scala, test/uk/gov/hmrc/cbcr/services/AdminServiceSpec.scala, test/uk/gov/hmrc/cbcr/services/RetrieveReportingEntityServiceSpec.scala, test/uk/gov/hmrc/cbcr/util/UnitSpec.scala
=> Stage 2: Schema version 2.0

app/uk/gov/hmrc/cbcr/models/ReportingRole.scala
=> [CU][DCWL-26]: Add CBC704 reporting entity role

app/uk/gov/hmrc/cbcr/connectors/DESConnector.scala
=> [CU][DLS-4142]: Remove duplicate headers

app/uk/gov/hmrc/cbcr/Module.scala, app/uk/gov/hmrc/cbcr/exceptions/ErrorLimitExceededException.scala, app/uk/gov/hmrc/cbcr/services/CBCXMLValidator.scala, build.sbt, conf/application.conf, conf/schema/2.0/CbcXML_v2.0.xsd, conf/schema/2.0/isocbctypes_v1.1.xsd, conf/schema/2.0/oecdcbctypes_v5.0.xsd, project/AppDependencies.scala, test/resources/cbcr-invalid-multiple-errors.xml, test/resources/cbcr-invalid-multiple-errors2.xml, test/resources/cbcr-invalid.xml, test/resources/cbcr-valid.xml, test/resources/fatal.xml, test/uk/gov/hmrc/cbcr/services/CBCXMLValidatorSpec.scala
Added EIS XML Schema Validation to CBCR backend.
=> DAC6-1028: add EIS XML Schema Validation to CBCR backend

test/uk/gov/hmrc/cbcr/repositories/UploadSessionRepositorySpec.scala
**Bug fix 
UploadSessionRepositorySpec tests fail intermittently due to race condition
=> DAC6-1070: Update UploadSessionRepositorySpec so that futures complete

app/uk/gov/hmrc/cbcr/controllers/FileUploadResponseController.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/DLS-7280)
=> DLS-7280 Log Race condition handling

app/uk/gov/hmrc/cbcr/Module.scala, app/uk/gov/hmrc/cbcr/auth/CBCRAuth.scala, app/uk/gov/hmrc/cbcr/connectors/DESConnector.scala, app/uk/gov/hmrc/cbcr/controllers/FileUploadResponseController.scala, app/uk/gov/hmrc/cbcr/controllers/test/TestSubscriptionDataController.scala, app/uk/gov/hmrc/cbcr/models/BusinessPartnerRecord.scala, app/uk/gov/hmrc/cbcr/models/CBCId.scala, app/uk/gov/hmrc/cbcr/models/CountryCode.scala, app/uk/gov/hmrc/cbcr/models/DatesOverlap.scala, app/uk/gov/hmrc/cbcr/models/DocRefID.scala, app/uk/gov/hmrc/cbcr/models/FileUploadResponse.scala, app/uk/gov/hmrc/cbcr/models/MessageRefId.scala, app/uk/gov/hmrc/cbcr/models/Migration.scala, app/uk/gov/hmrc/cbcr/models/ReportingEntityData.scala, app/uk/gov/hmrc/cbcr/models/ReportingRole.scala, app/uk/gov/hmrc/cbcr/models/SubscriptionData.scala, app/uk/gov/hmrc/cbcr/models/SubscriptionRequest.scala, app/uk/gov/hmrc/cbcr/models/TIN.scala, app/uk/gov/hmrc/cbcr/models/UltimateParentEntity.scala, app/uk/gov/hmrc/cbcr/models/Utr.scala, app/uk/gov/hmrc/cbcr/repositories/ReportingEntityDataRepo.scala, app/uk/gov/hmrc/cbcr/repositories/SubscriptionDataRepository.scala, app/uk/gov/hmrc/cbcr/services/AdminService.scala, app/uk/gov/hmrc/cbcr/services/EmailService.scala, app/uk/gov/hmrc/cbcr/services/LocalSubscription.scala
**DLS-6261**
Code clean-up including minor changes such as:
- Removing unnecessary {}
- Supplied the empty argument list `()
- Adding explicit types to implicits
- Replacing ⇒ with =>
=> Code cleanup

app/uk/gov/hmrc/cbcr/controllers/FileUploadResponseController.scala, app/uk/gov/hmrc/cbcr/repositories/FileUploadRepository.scala, test/uk/gov/hmrc/cbcr/controllers/FileUploadResponseControllerSpec.scala, test/uk/gov/hmrc/cbcr/repositories/FileUploadRepositorySpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/DLS-9551)
=> DLS-9551 Fitler FileUpload responses on write rather than on read.

app/uk/gov/hmrc/cbcr/controllers/FileUploadResponseController.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/DLS-9551)
=> DLS-9551 Allow ERROR status to come through

app/uk/gov/hmrc/cbcr/package.scala, app/uk/gov/hmrc/cbcr/services/RemoteSubscription.scala
Previously reviewed: https://github.com/hmrc/cbcr/pull/233
=> DLS-10422 Log des errors as exceptions
